### ISSUE TITLE
Error on OMOP to MEDS conversion

### ISSUE THREAD

**Issue by ealonso-vicomtech** [Medical-Event-Data-Standard/meds_etl#37]
Hi!

I am trying to execute the meds_etl_omop command to convert my OMOP dataset into MEDS but I'm getting the following error
```
Generating metadata from OMOP `concept` table
1it [00:06,  6.49s/it]
Decompressing OMOP tables, mapping to MEDS Flat format, writing to disk...
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                              | 4/5 [00:34<00:08,  8.63s/it]
Traceback (most recent call last):
  File "/data/venvs/lucia/bin/meds_etl_omop", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/venvs/lucia/lib/python3.11/site-packages/meds_etl/omop.py", line 747, in main
    process_table_csv(task)
  File "/data/venvs/lucia/lib/python3.11/site-packages/meds_etl/omop.py", line 379, in process_table_csv
    write_event_data(
  File "/data/venvs/lucia/lib/python3.11/site-packages/meds_etl/omop.py", line 315, in write_event_data
    event_data.sink_parquet(fname, compression="zstd", compression_level=1, maintain_order=False)
  File "/data/venvs/lucia/lib/python3.11/site-packages/polars/utils/unstable.py", line 59, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venvs/lucia/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2193, in sink_parquet
    return lf.sink_parquet(
           ^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: failed to determine supertype of list[extension] and datetime[μs]

Error originated just after this operation:
FILTER String(SNOMED/184099003).strict_cast(String).is_not_null() FROM
RENAME
  DF ["person_id", "gender_concept_id", "year_of_birth", "month_of_birth"]; PROJECT */18 COLUMNS; SELECTION: "None"

```

How can i deal with it? Looks like the error is related with the Person but i cannot see which columns have the unsuported type.

**Comment by ealonso-vicomtech** [comment]
Hi, 

Every concept_id in condition_occurrence table has a corresponding concept entry in concept table. 

I am using OMOP CDM v5.4 and all the condition_source_ids are standard (SNOMED vocab).

**Comment by mmcdermott** [comment]
@ealonso-vicomtech is this still an issue? If so, can you share more details about your data source, and/or see if you can provide an isolated set of synthetic data on which this issue occurs so we can help debug locally?
